passthruUnmapped: false

media:
  image:
    library:
      - src: https://images.microcms-assets.io/assets/
        kind: imgix

# items と total フィールドがルート直下になるように変形する.
transform: data.docsThemeCollectionCollection.items.collectionCollection

flds:
  - query: id
    dstName: id
    fldType: id

  - query: title
    dstName: title
    fldType: string

  # RichText(HTML) を Makrdown へ変換する.
  # Contentful では fldType=html の場合は `json` と `links` フィールドから変換する.
  - query: content
    dstName: content
    fldType: html
    convert: markdown
    toMarkdownOpts:
      # 画像の属性(widht と height)を alt 属性へ埋め込む.
      imageSalt:
        - command: embed
          baseURL: https://images.ctfassets.net/
          embed:
            embedTo: alt
      unusualSpaceChars: throw

  - query: description
    dstName: description
    fldType: string

  - query: category.title
    dstName: category
    fldType: string

  - query: fullscreen
    dstName: fullscreen
    fldType: boolean

  - query: version
    dstName: version
    fldType: string

  - query: menuTitle
    dstName: menuTitle
    fldType: string

  - query: subtitle
    dstName: subtitle
    fldType: string

  - query: badge
    dstName: badge
    fldType: string

  - query: list
    dstName: list
    fldType: object
