passthruUnmapped: false

media:
  image:
    library:
      - src: https://images.microcms-assets.io/assets/
        kind: imgix

# items と total フィールドがルート直下になるように変形する.
transform: data.docsThemeCollectionCollection.items.collectionCollection

flds:
  - srcName: id
    dstName: id
    fldType: id

  - srcName: title
    dstName: title
    fldType: string

  # RichText(HTML) を Makrdown へ変換する.
  # Contentful では fldType=html の場合は `json` と `links` フィールドから変換する.
  - srcName: content
    dstName: content
    fldType: html
    convert: markdown
    toMarkdownOpts:
      # 画像の属性(widht と height)を alt 属性へ埋め込む.
      embedImgAttrs:
        - baseURL: https://images.ctfassets.net/
          embedTo: alt

  - srcName: description
    dstName: description
    fldType: string

  - srcName: category.title
    dstName: category
    fldType: string

  - srcName: fullscreen
    dstName: fullscreen
    fldType: boolean

  - srcName: version
    dstName: version
    fldType: string

  - srcName: menuTitle
    dstName: menuTitle
    fldType: string

  - srcName: subtitle
    dstName: subtitle
    fldType: string

  - srcName: badge
    dstName: badge
    fldType: string

  - srcName: list
    dstName: list
    fldType: object
